engines:
  rubocop:
    enabled: true
    checks:
     Rubocop/Metrics/ClassLength:
       enabled: false
  golint:
    enabled: true
  phpmd:
    enabled: true
  eslint:
    enabled: true
    checks:
     max-statements:
      enabled: false
     complexity:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 8041cf293b665783523b6b498a128bf7
    - 07b3734de0fd9bbe0ff49d3fbb377f7d
    - dca27ded53320ef979eb1b3aea439d9c
    - f8ca8f9431eddf7e846e4d7838a64fdb
    config:
      languages:
      - php
      - javascript
      - css
ratings:
    paths:
    - "/**"
    - "**.php"
    - "**.css"
    - "**.html"
    - "**.js"
exclude_paths:
- "js/lib/openpgp.min.js"
- "js/lib/sha512.js"