engines:
  rubocop:
    enabled: true
    checks:
     Rubocop/Metrics/ClassLength:
       enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
    checks:
     max-statements:
      enabled: false
     complexity:
        enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
      - css
ratings:
    paths:
    - "/**"
    - "**.php"
    - "**.css"
    - "**.html"
    - "**.js"
exclude_paths:
- "js/lib/openpgp.min.js"
- "js/lib/sha512.js"